### ISSUE TITLE
pgfkeys Error

### ISSUE THREAD

**Issue by panovr** [zhanggyb/nndl#14]
I use TexLive 2015 and Ubuntu 14.04. After type "make", I got these errors:

 `(/usr/local/texlive/2015/texmf-dist/tex/generic/pgf/frontendlayer/tikz/librarie
s/tikzlibrarypositioning.code.tex)
No file bump_3d.aux.
ABD: EveryShipout initializing macros

Package pgfplots Warning: running in backwards compatibility mode (unsuitable t
ick labels; missing features). Consider writing \pgfplotsset{compat=1.12} into 
your preamble.
 on input line 8.

! Package pgfkeys Error: I do not know the key '/tikz/xtick distance', to which
 you passed '1', and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.62       \end{axis}

? 
`

**Comment by panovr** [comment]
After downloading pgf_3.0.1.tds.zip and pgfplots_1.13.tds.zip and installing them, the pgfkeys error is solved.

**Comment by zhanggyb** [comment]
Yes, the `xtick distance` should be a new feature in latest pgf package.

By the way, you can also use `$ tlmgr update --all` to update all tex packages.
