### ISSUE TITLE
A translation quesiton on Page 120

### ISSUE THREAD

**Issue by lpstudy** [zhanggyb/nndl#58]
感谢作者的辛勤工作

文中120页有一段话：
解决方案是设计一个神经网络，它的隐藏层有一个加权输出 σ−1 ◦ f(x)，其中 σ−1 是 σ 函数
的倒数。

这个地方"σ−1 " 使用倒数不太合适。 在我们普通人的观点里，f(x)的倒数是1/f(x)， 原文中说的是“the inverse of the σ function”，根据我的理解，这里应该还是反函数的意思。

**Comment by tigerneil** [comment]
谢谢指出 @lpstudy

**Comment by zhanggyb** [comment]
Fixed in version 0.4.
