### ISSUE TITLE
编译tikz8.tex出错

### ISSUE THREAD

**Issue by zzr0427** [zhanggyb/nndl#62]
用TeXworks单独编译这个文件的时候，显示“! LaTeX Error: Missing \begin{document}.”错误。把“\usepackage[default,mdseries=Light,bfseries=Medium,path=../fonts]{cjkfonts}”注释掉之后，正常编译，但字体就很丑了= =。可能是上面这个指令把“\begin{document}”淹没了。具体原因不详。

**Comment by zhanggyb** [comment]
你是在 Windows 中编译的吗？
这个项目目前只支持 Mac 和 Linux 下通过 `make` 命令编译。
也不会提供 GUI 工具的解答，这些工具都无法处理复杂的 TeX 项目。

把图形文件单独放在 images 目录是因为这些图形没有必要随着文档多次编译（LaTeX 需要编译多次才能生成 TOC, Index 等内容）。
如果你用 Mac 或者 Linux，可以执行一次 `make`，把 images/ 中的 pdf 图像拷贝出来用。

**Comment by zzr0427** [comment]
对的，我用windows编译的。不能使用make，所以我手动编译了images下的这些文件，来生成图片。tikz1.tex到tikz7.tex都没有问题。但是tikz8.tex因为包括了\usepackage所以编译不过，原因不详。我在linux下用make命令编译通过了。谢谢。
