### ISSUE TITLE
Mac运行bootstrap.sh

### ISSUE THREAD

**Issue by SilvesterHsu** [zhanggyb/nndl#72]
Mac运行bootstrap.sh删完了我系统的所以软件，运行的时候就觉得不对劲，怎么这么多rm命令。虽然及时停止了程序，但软件还是被删除了大部分😂

**Comment by zhanggyb** [comment]
抱歉，这可能是脚本的问题，但是我没法在我的 Mac 里复现这个问题。

**Comment by zhanggyb** [comment]
已经不再使用 bootstrap.sh 这个脚本
